CC := g++
RET_OPTION := -fno-elide-constructors

.PHYON: buildItem25, buildItem26, buildItem27


buildItem25: Item25.cpp
	@$(CC) $^ -o ./exe/Item25.exe $(RET_OPTION)

buildItem26: Item26.cpp
	@$(CC) $^ -o ./exe/Item26.exe 

buildItem27: Item27.cpp
	@$(CC) $^ -o ./exe/Item27.exe