.PHYON: build, run

build: Demo.cs AbstractProductA.cs AbstractProductB.cs ProductA1.cs ProductA2.cs ProductB1.cs ProductB2.cs AbstractFactory.cs ConcreteFactory1.cs ConcreteFactory2.cs
	@csc $^

run: Demo.exe
	@./Demo.exe