-- 计算日期与时间

-- 增加一天 
SELECT DATE_ADD(NOW(), INTERVAL 1 DAY);
-- 增加一月
SELECT DATE_ADD(NOW(), INTERVAL 1 MONTH);
-- 增加一年
SELECT DATE_ADD(NOW(), INTERVAL 1 YEAR);

-- 减少一天 
SELECT DATE_ADD(NOW(), INTERVAL -1 DAY);
SELECT DATE_SUB(NOW(), INTERVAL 1 DAY);
-- 减少一月
SELECT DATE_ADD(NOW(), INTERVAL -1 MONTH);
SELECT DATE_SUB(NOW(), INTERVAL 1 MONTH);
-- 减少一年
SELECT DATE_ADD(NOW(), INTERVAL -1 YEAR);
SELECT DATE_SUB(NOW(), INTERVAL 1 YEAR);

-- 计算间隔，前减去后，可能负数，只能计算日期间隔，到天，写了具体时间也没用
SELECT DATEDIFF('2019-02-02', '2022-02-22');
-- 计算时间间隔，返回 00:00 到指定时间的秒数
SELECT TIME_TO_SEC('09:00');
-- 计算两个具体时间的间隔，就要用两个 TIME_TO_SEC，前减后
SELECT TIME_TO_SEC('09:00') - TIME_TO_SEC('09:12');

