CC := g++


.PHYON: run_override run_mutable run_cast


run_override:
	@$(CC) OverrideByConst.cpp -o OverrideByConst.exe
	@./OverrideByConst.exe

run_mutable:
	@$(CC) Mutable.cpp -o Mutable.exe
	@./Mutable.exe

run_cast:
	@$(CC) Cast.cpp -o Cast.exe
	@./Cast.exe